name: pylint
on:
  push

env:
  DEFAULT_PYTHON_VERSION: '3.10'

jobs:
 black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - name: Setup Python.
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install poetry, and then install dependency of project.
        run: pip install poetry && poetry update && poetry install
      - name: Apply pylint.
        run: poetry run pylint space_game

 