name: unit-tests

on:
  push

jobs:
  pytest:
    strategy:
      matrix:
        operating_system: [ubuntu-latest, macos-latest, windows-latest]
        python_version: ['3.10']
    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
      - name: Setup Python.
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install poetry, and then install dependency of project.
        run: pip install poetry && poetry update && poetry install
      - name: Run unit tests with `pytest`.
        run: poetry run pytest
  
 